const Dialogs = [
  {
    title: "Parte 1",
    text: [
      ["Olá, pode me ajudar? Eu me chamo Brad e minha irmã foi sequestrada!", "left"],
      ["Me disseram que eu não posso chamar a polícia, então tem que ser você!", "left"],
      ["Ela se chama Lily e é minha irmã mais nova.", "left"],
      ["O que aconteceu? Ok, eu te conto!", "left"],
      [
        "Minha família sempre foi muito pobre e quando minha irmã nasceu, o nosso pai acabou indo embora.",
        "left",
      ],
      ["Nossa mãe teve que se virar para nos alimentar.", "left"],
      [
        "E ela conseguiu muito bem, mas a alguns dias nossa mãe foi diagnosticada com uma doença terrível.",
        "left",
      ],
      [
        "Cosmopólito de Savedra Vicinal, a doença é tão rara que quem ouvir o nome vai achar que é inventada.",
        "left",
      ],
      [
        "Enfim, ela foi internada as pressas e sua única esperança era uma injeção muito cara e que ainda estava em fase de testes.",
        "left",
      ],
      ["Tomado pelo medo, fui até o Sr. Malcon para pedir o dinheiro.", "left"],
      ["Depois de muito negociar acabei conseguindo e comprei a injeção.", "left"],
      [
        "Nossa mãe começou a se recuperar mas de repente ela acabou piorando, e piorou tanto que acabou não resistindo...",
        "left",
      ],
      ["Como a injeção era muito cara, não consegui pagar o agiota.", "left"],
      [
        "Então ele sequestrou a minha irmã e agora eu preciso da sua ajuda pra recuperá-la.",
        "left",
      ],
      ["Então você vai me ajudar? MUITO OBRIGADO...", "left"],
      ["Vamos lá, não sei onde o Sr Malcon está, mas conheço alguém que sabe!", "left"],
      ["Oh não, um capanga do Sr. Malcon, o cara que eu pedi dinheiro", "left"],
      ["Vamos ter que passar por ele!", "left"],
    ],
    images: [
      ["imgs/characters/user/Scared.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Sad.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Sad.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Sad.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Happy.png", ""],
      ["imgs/characters/user/Happy.png", ""],
      ["imgs/characters/user/Scared.png", ""],
      ["imgs/characters/user/Talking.png", ""],
    ],
    background: [
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
    ],
  },
  {
    title: "Parte 2",
    text: [
      ["Chegamos!", "left"],
      ["Que lugar é esse? É obvio pô, um bar", "left"],
      [
        "Ninguem conhece mais uma cidade do que um barman, ele com certeza sabe onde esta a Lily",
        "left",
      ],
      [
        "Uhh, já é de manhâ? Hm... Melhor eu voltar pra dentro se não os dois dragões ovelhas com chifre de galinha vão me comer...",
        "right",
      ],
      ["Dragões ovelhas com chifre de galinha? O cara está muito doido", "left"],
      [
        "Ow, o que foi que você disse? Me chamou de doido? Vem cá que eu te mostro quem é doido",
        "right",
      ],
    ],
    images: [
      ["imgs/characters/user/Talking.png", ""],
      ["imgs/characters/user/Talking.png", "imgs/characters/enemy_1/Idle.png"],
      ["imgs/characters/user/Talking.png", "imgs/characters/enemy_1/Idle.png"],
      ["imgs/characters/user/Scared.png", "imgs/characters/enemy_1/StrongAttack.png"],
      ["imgs/characters/user/Talking.png", "imgs/characters/enemy_1/Idle.png"],
      ["imgs/characters/user/Talking.png", "imgs/characters/enemy_1/LightAttack.png"],
    ],
    background: [
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
      "imgs/backgrounds/house.png",
    ],
  },
  {
    title: "Parte 3",
    text: [["Parabéns você finalizou este jogo!", "left"]],
    images: [["imgs/characters/user/Happy.png", ""]],
    background: ["imgs/backgrounds/house.png"],
  },
];
